#:schema node_modules/wrangler/config-schema.json
name = "golfscores"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npx @cloudflare/next-on-pages"
